## Importing Data: Working with CSV Files

In [1]:
import pandas as pd

In [29]:
df = pd.read_csv('model_logs.csv', encoding="utf-8")
df.head()

,Date,Prompt,Response Time (ms),Tokens Generated
0,2023-01-01,Generate a creative story about space travel,62,287
1,2023-01-02,Write a sci-fi short story set in 2050,45,361
2,2023-01-03,Write a poem about the future of technology,33,221
3,2023-01-04,Explain quantum computing in simple terms,53,290
4,2023-01-05,Explain quantum computing in simple terms,75,392

In [30]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Date                100 non-null    str
 1   Prompt              100 non-null    str
 2   Response Time (ms)  100 non-null    int64
 3   Tokens Generated    100 non-null    int64
dtypes: int64(2), str(2)
memory usage: 3.3 KB

In [31]:
df.describe()

       Response Time (ms)  Tokens Generated
count          100.000000        100.000000
mean            66.650000        342.930000
std             21.114108         90.095264
min             30.000000        203.000000
25%             47.500000        274.750000
50%             70.000000        324.500000
75%             86.000000        427.000000
max             99.000000        500.000000

In [32]:
df['Date'] = pd.to_datetime(df['Date'])

In [33]:
df

,Date,Prompt,Response Time (ms),Tokens Generated
0,2023-01-01,Generate a creative story about space travel,62,287
1,2023-01-02,Write a sci-fi short story set in 2050,45,361
2,2023-01-03,Write a poem about the future of technology,33,221
3,2023-01-04,Explain quantum computing in simple terms,53,290
4,2023-01-05,Explain quantum computing in simple terms,75,392
...,...,...,...,...
95,2023-04-06,Explain quantum computing in simple terms,61,304
96,2023-04-07,Write a sci-fi short story set in 2050,57,238
97,2023-04-08,Write a poem about the future of technology,38,465
98,2023-04-09,Generate marketing copy for a new tech product,77,296
99,2023-04-10,Create a recipe using plant-based ingredients,55,306

In [34]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Date                100 non-null    datetime64[us]
 1   Prompt              100 non-null    str
 2   Response Time (ms)  100 non-null    int64
 3   Tokens Generated    100 non-null    int64
dtypes: datetime64[us](1), int64(2), str(1)
memory usage: 3.3 KB

In [35]:
df['Response Time (ms)'] = df['Response Time (ms)'].astype(float)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Date                100 non-null    datetime64[us]
 1   Prompt              100 non-null    str
 2   Response Time (ms)  100 non-null    float64
 3   Tokens Generated    100 non-null    int64
dtypes: datetime64[us](1), float64(1), int64(1), str(1)
memory usage: 3.3 KB

In [36]:
df

,Date,Prompt,Response Time (ms),Tokens Generated
0,2023-01-01,Generate a creative story about space travel,62.0,287
1,2023-01-02,Write a sci-fi short story set in 2050,45.0,361
2,2023-01-03,Write a poem about the future of technology,33.0,221
3,2023-01-04,Explain quantum computing in simple terms,53.0,290
4,2023-01-05,Explain quantum computing in simple terms,75.0,392
...,...,...,...,...
95,2023-04-06,Explain quantum computing in simple terms,61.0,304
96,2023-04-07,Write a sci-fi short story set in 2050,57.0,238
97,2023-04-08,Write a poem about the future of technology,38.0,465
98,2023-04-09,Generate marketing copy for a new tech product,77.0,296
99,2023-04-10,Create a recipe using plant-based ingredients,55.0,306

In [37]:
mask = df['Response Time (ms)'] > 50
slow_responses = df[mask]
slow_responses

,Date,Prompt,Response Time (ms),Tokens Generated
0,2023-01-01,Generate a creative story about space travel,62.0,287
3,2023-01-04,Explain quantum computing in simple terms,53.0,290
4,2023-01-05,Explain quantum computing in simple terms,75.0,392
5,2023-01-06,Generate marketing copy for a new tech product,61.0,250
6,2023-01-07,Write a sci-fi short story set in 2050,87.0,370
...,...,...,...,...
93,2023-04-04,Explain quantum computing in simple terms,97.0,325
95,2023-04-06,Explain quantum computing in simple terms,61.0,304
96,2023-04-07,Write a sci-fi short story set in 2050,57.0,238
98,2023-04-09,Generate marketing copy for a new tech product,77.0,296
99,2023-04-10,Create a recipe using plant-based ingredients,55.0,306

### Export the Data to CSV File

In [38]:


slow_responses.to_csv('slow_responses.csv', index=False)

### Export the Data to Excel Sheet

In [39]:
pip install openpyxl

Requirement already satisfied: openpyxl in .\venv\Lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in .\venv\Lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

In [40]:
# slow_responses = slow_responses.applymap(lambda x: str(x).encode("utf-8", "ignore").decode("utf-8") if isinstance(x, str) else x)

slow_responses.to_excel('data.xlsx', index=False)

###  Exporting to JSON

In [42]:
slow_responses.to_json('data.json', orient='columns')

C:\Users\gvenk\AppData\Local\Temp\ipykernel_29052\173094832.py:1: Pandas4Warning: The default 'epoch' date format is deprecated and will be removed in a future version, please use 'iso' date format instead.
  slow_responses.to_json('data.json', orient='columns')

###  Exporting to YAML

In [44]:
import yaml

data_dict = slow_responses.to_dict(orient='records')

In [46]:
with open('slow_responses.yaml', 'w') as file:
    yaml.dump(data_dict, file)