##  Modifying Data: Adding and Dropping Columns and Rows

In [2]:
import pandas as pd

# Sample DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35]
}
df = pd.DataFrame(data)

In [3]:
df

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [5]:
df['City'] = ['New York', 'Los Angeles', 'Chicago']

In [7]:
df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [8]:
df['Age Group'] = ['Young' if age < 30 else 'Mature' for age in df['Age']]

In [9]:
df

      Name  Age         City Age Group
0    Alice   25     New York     Young
1      Bob   30  Los Angeles    Mature
2  Charlie   35      Chicago    Mature

#### axis 0 is row and 1 is column

In [11]:
df = df.drop('Age Group', axis=1)

In [12]:
df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [13]:
df = df.drop(1)

In [14]:
df

      Name  Age      City
0    Alice   25  New York
2  Charlie   35   Chicago

In [15]:
df_copy = df.copy()

In [16]:
df_copy

      Name  Age      City
0    Alice   25  New York
2  Charlie   35   Chicago

In [19]:
df.assign(Discount=[5, 10], Total_Spend=[100, 200])

      Name  Age      City  Discount  Total_Spend
0    Alice   25  New York         5          100
2  Charlie   35   Chicago        10          200

In [20]:
df_copy

      Name  Age      City
0    Alice   25  New York
2  Charlie   35   Chicago

## Accessing Data: Using df.iloc[] and df.loc[]

In [47]:
# Sample DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 30, 35, 40, 45],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Seattle']
}
df = pd.DataFrame(data)

In [39]:
df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston
4      Eva   45      Seattle

In [45]:
row = df.loc[1]
row

Name            Bob
Age              30
City    Los Angeles
Name: 1, dtype: object

In [51]:
col = df.loc[0, 'City']
col

'New York'

In [48]:
df_tmp = df.loc[1:4]

In [50]:
df_tmp

      Name  Age         City
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston
4      Eva   45      Seattle

In [61]:
mask = df['Age'] > 30
filtered = df.loc[mask].iloc[:, 2]
filtered

2    Chicago
3    Houston
4    Seattle
Name: City, dtype: str

In [58]:
df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston
4      Eva   45      Seattle

In [66]:
df.iloc[1:4]

      Name  Age         City
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston

##  Sampling and Previewing Data: Using df.sample() and df.head()

In [69]:
import pandas as pd
df = pd.read_csv('model_logs.csv')

In [70]:
df.head()

,Date,Prompt,Response Time (ms),Tokens Generated
0,2023-01-01,Generate a creative story about space travel,62,287
1,2023-01-02,Write a sci-fi short story set in 2050,45,361
2,2023-01-03,Write a poem about the future of technology,33,221
3,2023-01-04,Explain quantum computing in simple terms,53,290
4,2023-01-05,Explain quantum computing in simple terms,75,392

In [71]:
df.head(1)

,Date,Prompt,Response Time (ms),Tokens Generated
0,2023-01-01,Generate a creative story about space travel,62,287

In [72]:
df.head(3)

,Date,Prompt,Response Time (ms),Tokens Generated
0,2023-01-01,Generate a creative story about space travel,62,287
1,2023-01-02,Write a sci-fi short story set in 2050,45,361
2,2023-01-03,Write a poem about the future of technology,33,221

In [75]:
random_rows = df.sample()
random_rows

,Date,Prompt,Response Time (ms),Tokens Generated
43,2023-02-13,Describe the impact of AI on healthcare,92,362

In [85]:
random_rows = df.sample(n=5)
random_rows

,Date,Prompt,Response Time (ms),Tokens Generated
23,2023-01-24,Outline the ethical considerations of AI,53,301
58,2023-02-28,Create a recipe using plant-based ingredients,86,276
80,2023-03-22,Explain blockchain for beginners,90,226
94,2023-04-05,Summarize the latest research on climate change,41,500
82,2023-03-24,Create a recipe using plant-based ingredients,88,206

In [86]:
random_rows = df.sample(n=10, random_state=9)
random_rows

,Date,Prompt,Response Time (ms),Tokens Generated
75,2023-03-17,Describe the impact of AI on healthcare,83,208
42,2023-02-12,Outline the ethical considerations of AI,41,499
46,2023-02-16,Describe the impact of AI on healthcare,73,302
68,2023-03-10,Explain blockchain for beginners,59,316
3,2023-01-04,Explain quantum computing in simple terms,53,290
39,2023-02-09,Outline the ethical considerations of AI,33,286
23,2023-01-24,Outline the ethical considerations of AI,53,301
20,2023-01-21,Write a poem about the future of technology,36,390
70,2023-03-12,Explain quantum computing in simple terms,80,450
73,2023-03-15,Explain blockchain for beginners,91,293

In [89]:
random_rows = df.sample(frac=0.1, random_state=9)
random_rows

,Date,Prompt,Response Time (ms),Tokens Generated
75,2023-03-17,Describe the impact of AI on healthcare,83,208
42,2023-02-12,Outline the ethical considerations of AI,41,499
46,2023-02-16,Describe the impact of AI on healthcare,73,302
68,2023-03-10,Explain blockchain for beginners,59,316
3,2023-01-04,Explain quantum computing in simple terms,53,290
39,2023-02-09,Outline the ethical considerations of AI,33,286
23,2023-01-24,Outline the ethical considerations of AI,53,301
20,2023-01-21,Write a poem about the future of technology,36,390
70,2023-03-12,Explain quantum computing in simple terms,80,450
73,2023-03-15,Explain blockchain for beginners,91,293

## Filtering Data: Masks and pandas.Series.between()

In [90]:
import pandas as pd

# Sample DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 30, 35, 40, 45],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Miami']
}
df = pd.DataFrame(data)

In [91]:
df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston
4      Eva   45        Miami

In [92]:
mask = df['Age'] > 30

In [93]:
mask

0    False
1    False
2     True
3     True
4     True
Name: Age, dtype: bool

In [94]:
filtered_df = df[mask]
filtered_df

      Name  Age     City
2  Charlie   35  Chicago
3    David   40  Houston
4      Eva   45    Miami

In [95]:
df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston
4      Eva   45        Miami

In [97]:
mask = (df['Age'] > 30) & (df['City'] == 'Houston')
filtered_df = df[mask]
filtered_df

    Name  Age     City
3  David   40  Houston

In [98]:
df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston
4      Eva   45        Miami

In [99]:
mask = df['Age'].between(30, 40)
filtered_df = df[mask]
filtered_df

      Name  Age         City
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston

In [100]:
df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston
4      Eva   45        Miami

In [102]:
mask = df['City'].isin(['Los Angeles', 'Houston'])
filtered_df = df[mask]
filtered_df

    Name  Age         City
1    Bob   30  Los Angeles
3  David   40      Houston