In [7]:
import pandas as pd

# Sample DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 30, 35, 40, 45],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Chicago']
}
df = pd.DataFrame(data)

In [2]:
df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston
4      Eva   45        Miami

In [3]:
sorted_df = df.sort_values(by='Age')
sorted_df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston
4      Eva   45        Miami

In [4]:
sorted_df = df.sort_values(by='Age', ascending=False)
sorted_df

      Name  Age         City
4      Eva   45        Miami
3    David   40      Houston
2  Charlie   35      Chicago
1      Bob   30  Los Angeles
0    Alice   25     New York

In [5]:
sorted_df = df.sort_values(by='City')
sorted_df

      Name  Age         City
2  Charlie   35      Chicago
3    David   40      Houston
1      Bob   30  Los Angeles
4      Eva   45        Miami
0    Alice   25     New York

In [8]:
sorted_df = df.sort_values(by=['City', 'Age'])
sorted_df

      Name  Age         City
2  Charlie   35      Chicago
4      Eva   45      Chicago
3    David   40      Houston
1      Bob   30  Los Angeles
0    Alice   25     New York

In [9]:
sorted_df = df.sort_index()
sorted_df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston
4      Eva   45      Chicago

In [10]:
# Example DataFrame: Player leaderboard with names and scores
data = {
    'Player': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve'],
    'Score': [150, 200, 125, 300, 175]
}
df = pd.DataFrame(data)
df

    Player  Score
0    Alice    150
1      Bob    200
2  Charlie    125
3    Diana    300
4      Eve    175

In [14]:
sorted_df = df.sort_values(by='Score', ascending=False).reset_index(drop=True)
sorted_df['Rank'] = sorted_df.index + 1
sorted_df

    Player  Score  Rank
0    Diana    300     1
1      Bob    200     2
2      Eve    175     3
3    Alice    150     4
4  Charlie    125     5

## Handling Missing Data

In [15]:
import pandas as pd
# Sample DataFrame with missing values
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana'],
    'Age': [25, None, 35, 40],
    'City': ['New York', 'Los Angeles', None, 'Houston']
}
df = pd.DataFrame(data)

In [16]:
df

      Name   Age         City
0    Alice  25.0     New York
1      Bob   NaN  Los Angeles
2  Charlie  35.0          NaN
3    Diana  40.0      Houston

In [17]:
df.isnull()

    Name    Age   City
0  False  False  False
1  False   True  False
2  False  False   True
3  False  False  False

In [18]:
df.isna()

    Name    Age   City
0  False  False  False
1  False   True  False
2  False  False   True
3  False  False  False

In [20]:
df_cleaned = df.dropna()
df_cleaned

    Name   Age      City
0  Alice  25.0  New York
3  Diana  40.0   Houston

In [21]:
df_cleaned = df.dropna(axis=1)
df_cleaned

      Name
0    Alice
1      Bob
2  Charlie
3    Diana

In [22]:
df

      Name   Age         City
0    Alice  25.0     New York
1      Bob   NaN  Los Angeles
2  Charlie  35.0          NaN
3    Diana  40.0      Houston

In [23]:
df['Age'] = df['Age'].fillna(df['Age'].mean())
df

      Name        Age         City
0    Alice  25.000000     New York
1      Bob  33.333333  Los Angeles
2  Charlie  35.000000          NaN
3    Diana  40.000000      Houston

In [24]:
df

      Name        Age         City
0    Alice  25.000000     New York
1      Bob  33.333333  Los Angeles
2  Charlie  35.000000          NaN
3    Diana  40.000000      Houston

In [25]:
df['City'] = df['City'].fillna('Unknown')
df

      Name        Age         City
0    Alice  25.000000     New York
1      Bob  33.333333  Los Angeles
2  Charlie  35.000000      Unknown
3    Diana  40.000000      Houston

In [26]:
df.isnull()

    Name    Age   City
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False

## Aggregations and Grouping Data

In [27]:
import pandas as pd
# Sample DataFrame
data = {
    'Category': ['Electronics', 'Electronics', 'Furniture', 'Furniture', 'Apparel'],
    'Product': ['Laptop', 'Mouse', 'Chair', 'Table', 'Shoes'],
    'Sales': [1200, 100, 400, 300, 50]
}
df = pd.DataFrame(data)

In [28]:
df

      Category Product  Sales
0  Electronics  Laptop   1200
1  Electronics   Mouse    100
2    Furniture   Chair    400
3    Furniture   Table    300
4      Apparel   Shoes     50

In [39]:
grouped_df = df.groupby('Category')['Sales'].sum().reset_index()
grouped_df

      Category  Sales
0      Apparel     50
1  Electronics   1300
2    Furniture    700

In [40]:
grouped_df = df.groupby(['Category','Product'])['Sales'].sum()
grouped_df

Category     Product
Apparel      Shoes        50
Electronics  Laptop     1200
             Mouse       100
Furniture    Chair       400
             Table       300
Name: Sales, dtype: int64

In [42]:
summary = df.groupby('Category')['Sales'].agg(['sum', 'count', 'mean'])
summary

              sum  count   mean
Category
Apparel        50      1   50.0
Electronics  1300      2  650.0
Furniture     700      2  350.0