## Time Series Data Manipulation in Pandas

In [1]:
import pandas as pd

# Sample DataFrame
data = {
    'OrderID': [1001, 1002, 1003, 1004],
    'OrderDate': ['2023-11-01', '2023-11-02', '2023-11-03', '2023-11-04'],
    'Sales': [250, 400, 150, 300]
}
df = pd.DataFrame(data)

In [2]:
df

   OrderID   OrderDate  Sales
0     1001  2023-11-01    250
1     1002  2023-11-02    400
2     1003  2023-11-03    150
3     1004  2023-11-04    300

In [3]:
df.dtypes

OrderID      int64
OrderDate      str
Sales        int64
dtype: object

In [4]:
df['OrderDate'] = pd.to_datetime(df['OrderDate'])
df

   OrderID  OrderDate  Sales
0     1001 2023-11-01    250
1     1002 2023-11-02    400
2     1003 2023-11-03    150
3     1004 2023-11-04    300

In [5]:
df.dtypes

OrderID               int64
OrderDate    datetime64[us]
Sales                 int64
dtype: object

In [7]:
df.set_index('OrderDate', inplace=True)
df

            OrderID  Sales
OrderDate
2023-11-01     1001    250
2023-11-02     1002    400
2023-11-03     1003    150
2023-11-04     1004    300

In [9]:
df['Year'] = df.index.year
df['Month'] = df.index.month
df['Day'] = df.index.day
df

            OrderID  Sales  Year  Month  Day
OrderDate
2023-11-01     1001    250  2023     11    1
2023-11-02     1002    400  2023     11    2
2023-11-03     1003    150  2023     11    3
2023-11-04     1004    300  2023     11    4

In [10]:
weekly_sales = df['Sales'].resample('W').sum()
weekly_sales

OrderDate
2023-11-05    1100
Freq: W-SUN, Name: Sales, dtype: int64

In [11]:
df = pd.read_csv('website_traffic_data_datetime.csv')

In [12]:
df

      Source  SessionDuration  Visits        Date
0     Direct            27.53     267  2023-01-01
1   Referral            25.65     476  2023-01-02
2     Social            14.03     441  2023-01-03
3   Referral             3.77     473  2023-01-04
4   Referral            11.75     434  2023-01-05
..       ...              ...     ...         ...
95    Social             3.79     226  2023-04-06
96  Referral            28.28     277  2023-04-07
97      Paid            12.53     286  2023-04-08
98      Paid            16.01      97  2023-04-09
99   Organic            25.29     284  2023-04-10

[100 rows x 4 columns]

In [13]:
df['Date'] = pd.to_datetime(df['Date'])

In [14]:
df

      Source  SessionDuration  Visits       Date
0     Direct            27.53     267 2023-01-01
1   Referral            25.65     476 2023-01-02
2     Social            14.03     441 2023-01-03
3   Referral             3.77     473 2023-01-04
4   Referral            11.75     434 2023-01-05
..       ...              ...     ...        ...
95    Social             3.79     226 2023-04-06
96  Referral            28.28     277 2023-04-07
97      Paid            12.53     286 2023-04-08
98      Paid            16.01      97 2023-04-09
99   Organic            25.29     284 2023-04-10

[100 rows x 4 columns]

In [15]:
df.set_index('Date', inplace=True)
df

              Source  SessionDuration  Visits
Date
2023-01-01    Direct            27.53     267
2023-01-02  Referral            25.65     476
2023-01-03    Social            14.03     441
2023-01-04  Referral             3.77     473
2023-01-05  Referral            11.75     434
...              ...              ...     ...
2023-04-06    Social             3.79     226
2023-04-07  Referral            28.28     277
2023-04-08      Paid            12.53     286
2023-04-09      Paid            16.01      97
2023-04-10   Organic            25.29     284

[100 rows x 3 columns]

In [16]:
monthly_visits = df['Visits'].resample('ME').sum()
monthly_visits

Date
2023-01-31    7813
2023-02-28    7137
2023-03-31    8384
2023-04-30    2233
Freq: ME, Name: Visits, dtype: int64

In [17]:
monthly_visits = df['Visits'].resample('W').sum()
monthly_visits

Date
2023-01-01     267
2023-01-08    2868
2023-01-15    1514
2023-01-22    1514
2023-01-29    1138
2023-02-05    1373
2023-02-12    1749
2023-02-19    1932
2023-02-26    2091
2023-03-05    1973
2023-03-12    1901
2023-03-19    1668
2023-03-26    2317
2023-04-02    1518
2023-04-09    1460
2023-04-16     284
Freq: W-SUN, Name: Visits, dtype: int64

# Panadas Project: Analyzing Website Traffic Data

In [20]:
import pandas as pd

df = pd.read_csv('website_traffic_data.csv')
df

      Source  SessionDuration
0    Organic             8.15
1    Organic            17.28
2     Direct             8.62
3       Paid            17.95
4       Paid            27.04
..       ...              ...
95  Referral            24.42
96  Referral             6.52
97      Paid             3.81
98    Direct            13.50
99      Paid            13.28

[100 rows x 2 columns]

In [25]:
grouped_data = df.groupby('Source')
average_duration = grouped_data['SessionDuration'].sum()
average_duration

Source
Direct      333.33
Organic     378.87
Paid        301.00
Referral    217.28
Social      273.13
Name: SessionDuration, dtype: float64